FROM node:lts-alpine

WORKDIR /laetis-diner

COPY package.json .
COPY yarn.lock .

ENV HOST 0.0.0.0
ENV PORT 3000
ENV API https://laetis-diner-api.herokuapp.com/
ENV NODE_ENV=production

COPY . /laetis-diner
RUN yarn


RUN yarn build

EXPOSE 3000