FROM node:lts-alpine

WORKDIR /laetis-diner

COPY package.json .
COPY yarn.lock .

ENV NODE_ENV=production
ENV HOST 0.0.0.0
ENV PORT 3000
ENV API https://laetis-diner-api.herokuapp.com/

COPY . /laetis-diner
RUN yarn

RUN yarn build

EXPOSE 3000