query recipe($id: Int!) {
   recipe(id: $id) {
      id
      title

      image

      categories {
         id
         name
      }
      difficulty
      done

      preparation_time
      rest_time
      baking_time
      # total_time

      servings
      ingredients
      utensils

      preparation_steps

      notes
   }
}
